### ISSUE TITLE
How to pause?

### ISSUE THREAD

**Issue by KyleChongHengKai** [ForgedCore8/OSZsave#2]
this tool is great! i appreciate your work, however the downloading of the beatmaps takes way too long. It would be nice if you shortened the sleep time after each download, allow bulk downloads and make a way to pause the task

**Comment by bytewired9** [comment]
Came across this issue purely by chance. I actually made this quicker in an unreleased version so I'll push it soon! (ETA 2ish hours)

**Comment by bytewired9** [comment]
So it WOULD have been 2 hours, but I'm a perfectionist. Gonna be one more day

**Comment by bytewired9** [comment]
Fixed in 1.4.0
